"""
Settlement Engine – Generates optimized settlement recommendations.

Uses a greedy min-transactions algorithm:
1. Calculate net balances
2. Separate into creditors and debtors
3. Sort both by amount (descending)
4. Match largest debtor with largest creditor
5. Transfer min(debt, credit), reduce both
6. Repeat until all balances are settled

This minimizes the total number of transactions needed.
"""

from datetime import date

from database.database import SessionLocal
from database.models import Settlement, User
from services.balance_engine import (
    calculate_balances,
    calculate_all_balances,
    get_creditors_and_debtors,
)


# =====================================================
# GENERATE OPTIMIZED SETTLEMENTS
# =====================================================

def generate_settlements(group_id, db):
    """
    Generate optimized settlement recommendations
    for a specific group.

    Returns list of:
    {
        "from_id": int,
        "from_name": str,
        "to_id": int,
        "to_name": str,
        "amount": float,
    }
    """
    if group_id:
        balances = calculate_balances(group_id, db)
    else:
        balances = calculate_all_balances(db)

    creditors, debtors = get_creditors_and_debtors(balances)

    return _optimize_settlements(creditors, debtors)


def generate_all_settlements(db):
    """
    Generate optimized settlement recommendations
    across ALL groups.
    """
    balances = calculate_all_balances(db)
    creditors, debtors = get_creditors_and_debtors(balances)

    return _optimize_settlements(creditors, debtors)


# =====================================================
# GREEDY MIN-TRANSACTIONS ALGORITHM
# =====================================================

def _optimize_settlements(creditors, debtors):
    """
    Greedy algorithm to minimize the number of
    settlement transactions.

    Takes creditors and debtors lists and returns
    optimized settlement recommendations.
    """
    settlements = []

    # Make mutable copies
    creds = [
        [uid, name, amount]
        for uid, name, amount in creditors
    ]

    debts = [
        [uid, name, amount]
        for uid, name, amount in debtors
    ]

    ci = 0  # creditor index
    di = 0  # debtor index

    while ci < len(creds) and di < len(debts):

        creditor = creds[ci]
        debtor = debts[di]

        # Transfer the minimum of what's owed
        transfer = min(creditor[2], debtor[2])

        if transfer > 0.01:  # Threshold for float noise
            settlements.append({
                "from_id": debtor[0],
                "from_name": debtor[1],
                "to_id": creditor[0],
                "to_name": creditor[1],
                "amount": round(transfer, 2),
            })

        # Reduce balances
        creditor[2] -= transfer
        debtor[2] -= transfer

        # Move to next if fully settled
        if creditor[2] < 0.01:
            ci += 1

        if debtor[2] < 0.01:
            di += 1

    return settlements


# =====================================================
# APPLY SETTLEMENT
# =====================================================

def apply_settlement(from_id, to_id, amount, db, group_id=None):
    """
    Record a settlement recommendation as an actual
    Settlement in the database.
    """
    settlement = Settlement(
        group_id=group_id,
        payer_id=from_id,
        receiver_id=to_id,
        amount=amount,
        settlement_date=date.today(),
        notes="Auto-generated by SettleWise",
    )

    db.add(settlement)
    db.commit()

    return settlement


def apply_all_settlements(recommendations, db, group_id=None):
    """
    Record all recommended settlements at once.
    """
    recorded = []

    for rec in recommendations:

        settlement = Settlement(
            group_id=group_id,
            payer_id=rec["from_id"],
            receiver_id=rec["to_id"],
            amount=rec["amount"],
            settlement_date=date.today(),
            notes="Auto-generated by SettleWise",
        )

        db.add(settlement)
        recorded.append(settlement)

    db.commit()

    return recorded
